snapshot-labs/sx-ui

src/views/Space/Treasury.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/141
Adds total value of Treasury under the address.
=> feat: display Treasury total value

src/components/Block/ExecutionEditable.vue, src/components/Modal/SendNft.vue, src/components/Modal/SendToken.vue, src/components/Modal/Transaction.vue, src/components/S/IObject.vue, src/components/S/IString.vue, src/helpers/__tests__/__snapshots__/transactions.test.ts.snap, src/helpers/transactions.ts, src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/165
- Update `IObject` and `IString` to properly do two-way binding (same as changes in INumber before).
- Update TransactionModal to use `computed` values so it better handles data coming from two places.
- Bugfixes in TransactionModal that handle issues when switching methods on already populated forms or when ABI gets updated.
- Add edit option to all transaction types.
- Add bunch of transactions (token, nfts, contract calls).
- Try editing some of them (changing recipients, values, tokens, different contracts, methods etc.).
- Nothing should go terribly wrong.
I used those two contracts to get ABIs:
- `0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6`
- `0x11fE4B6AE13d2a6055C8D9cF65c55bac32B5d844`
=> feat: make proposal transactions editable

package.json, src/components/Modal/Transaction.vue, src/components/S/Base.vue, src/components/S/IBoolean.vue, src/components/S/INumber.vue, src/components/S/IObject.vue, src/components/S/IString.vue, src/helpers/utils.ts, src/helpers/validation.ts, src/style.scss, tailwind.config.js, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/164
Adds validation for forms using ajv schema.
- Validation is done at top level and components just react to `error` prop. It could be possible to do it at the component level (as those components already receive definitions), but getting validation status out of deeper components back seems weird and it seems most libraries do it at top level.
- Fixed components checking wrong prop for defaultValue, became apparent after enabling TS.
- Go to Contract call modal.
- Invalid contract address should give you error message.
- Input correct address.
- Inputting invalid address or uint256 into args should result in error message as well
=> feat: add form validation

src/components/Block/ExecutionEditable.vue, src/composables/useActions.ts, src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/183
- Added missing required `itemKey` prop, we don't have a good key to use for those, but we can use function to opt-out to default Vue keying.
- Nonce and operation are added when those are submitted to IPFS as those are derivatives or existing data in UI so it doesn't make sense to add it outside of it and would make it harder to work with (making sure we keep those in sync when we add/remove/reorder entries).
=> feat: add nonce and operation to proposal file

src/components/Modal/Transaction.vue, src/helpers/__tests__/__snapshots__/transactions.test.ts.snap, src/helpers/__tests__/transactions.test.ts, src/helpers/transactions.ts, src/helpers/validation.ts, src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/178
- add contract call to `0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6`.
- `deposit` method has payable field, `transfer` doesn't.
- add `deposit` method call with amount.
- when editing the amount is there.
- log all `execution` it should contain `value` for calls with payable methods.
=> feat: handle payable methods

src/components/Modal/Transaction.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/179
- throw before `getABI` call
- insert some address (`0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6`)
- input shows up, insert JSON ABI (https://www.smartcontracttoolkit.com/abi)
- you can now pick and use methods from ABI
- you can save transaction
https://user-images.githubusercontent.com/1968722/180624291-6013bae2-8358-4bb0-95d7-f683ac85f513.mov
=> feat: add manual ABI input

src/components/Block/TokenPicker.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/188
- Searching for `0xba100000625a3754423978a60c9317c58a424e3D` should return BAL.
=> feat: add contract address based search in token picker

src/helpers/queries.ts, src/types.ts, src/views/Space/Overview.vue, src/views/Space/Proposals.vue
Currently each space page displays all proposals, not filtered by space.
- Go to space page
- You only see proposals for that space.
=> feat: filter proposals by space

.env, package.json, src/composables/useActions.ts, src/helpers/clients.ts, src/helpers/constants.ts, yarn.lock
Closes: #288
I hardcoded executor + authenticator for now. We will need to update `sx-api` to return those in better format (right now it's string-encoded array. And it would be nice to use some state (Vuex) to persist spaces/proposals so we can easily access them when we need to vote/propose.
Use this mana: https://github.com/snapshot-labs/mana/pull/79
Use ethSig spaces for now as authenticator is hardcoded.
- Create proposal
- Vote on proposal
=> feat: use latest @snapshot-labs/sx

package.json, src/components/Proposal.vue, src/components/Sidebar.vue, src/composables/useAccount.ts, src/composables/useEditor.ts, src/main.ts, src/stores/proposals.ts, src/stores/spaces.ts, src/types.ts, src/views/Home.vue, src/views/Proposal.vue, src/views/Space.vue, src/views/Space/Overview.vue, src/views/Space/Proposals.vue, tsconfig.json, yarn.lock
Closes https://github.com/snapshot-labs/sx-ui/issues/312
- Added Pinia.
- Migrated Spaces/Proposals to fetch data from Pinia action to global store.
- Renamed old `Proposal` type to `Draft`.
- Go to Homepage - spaces load in sidebar and homepage.
- Click space - it loads instantly (only proposals are loading).
- Refresh page. Space is displayed.
- Click Proposals on the right. It displays proposals without refetching.
- Click on proposal - it loads instantly.
- Refresh page. Proposal is displayed.
=> feat: use Pinia to fetch spaces and proposals

.eslintrc.js, package.json, src/App.vue, src/router.ts
- Make prettier ruler errors.
- Update eslint path so it runs on files directly in `src` too.
- Reformat files that are not properly formatted.
=> chore: enforce prettier to pass

.eslintrc.js, src/components/Proposal.vue, src/components/Results.vue, src/components/Vote.vue, src/composables/useAccount.ts, src/helpers/constants.ts, src/helpers/queries.ts, src/types.ts, src/views/Proposal.vue
This PR adds Vote component that unifies logic for handling voting edge cases:
- User already voted for proposal
- Proposal is not supported (unsupported authenticators/strategies).
With this component you just provide different UI for those cases so you don't have to worry that in some place you can vote when you shouldn't.
This PR also makes Vote ratio to show up again.
- In Space view, proposals that were already voted on have vote ratio displayed.
- In Space view, proposals that are unsupported (go to Tripod DAO) don't have buttons to vote.
- In Space view, other proposals have vote buttons visible.
- In Proposal view, proposals that were already voted have "You have already voted for this proposal" message.
- In Proposal view, proposals that are unsupported (go to Tripod DAO) have …
=> feat: add Vote component

src/components/Block/NftPicker.vue, src/components/Modal/SendNft.vue, src/components/NftPreview.vue, src/composables/useNfts.ts, src/helpers/__tests__/transactions.test.ts, src/helpers/transactions.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/315
=> feat: use OpenSea for fetching NFTs

src/composables/useBalances.ts, src/helpers/space.json, src/style.scss, src/views/Proposal.vue, src/views/Space/Settings.vue, src/views/Space/Treasury.vue
This are some small improvement on treasury page, adding the tokens price and 24h % change along with improving the proposal page and settings style.
Treasury looks like this:
(ETH was working previously, might be something wrong with Covalent atm as it doesn't return the price quote)
Proposal page:
=> feat: Add token price and 24h change in treasury page

src/components/Block/ExecutionEditable.vue, src/components/Modal/SendToken.vue, src/composables/useBalances.ts, src/composables/useNfts.ts, src/helpers/space.json, src/views/Space/Treasury.vue
Changing the hardcoded treasury address to the space L1 controlled Safe, this is to make it easier to test execution later.
=> refactor: Change treasury address to Goerli owned Safe

src/components/Block/ContactPicker.vue, src/components/Modal/SendNft.vue, src/components/Modal/SendToken.vue, src/components/Modal/Transaction.vue, src/components/S/IAddress.vue, src/components/S/IObject.vue, src/components/S/IString.vue, src/composables/useAccount.ts, src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/185
Long term I think it would make sense to create a more robust modal system that can render them at will, outside of main tree so we could just do `const result = await showContactPicker()`. That would improve reusability of modals a lot (right now they need to repeat some of the UI). I have no idea how to do it now, seems common with React/Redux, but for Vue it seems it's never done like that.
- Open different modal types, you can pick address in there.
- Open Contract modal.
- Pick WETH contract and `transferFrom` method.
- You can pick different addresses from picker.
=> feat: add ContactPicker

src/composables/useActions.ts, src/networks/starknet/actions.ts, src/types.ts
This PR makes execution through ethRelayer functional. As of now I only tested sending ETH out.
- Create proposal with ETH transfer as execution.
For full test plan with execution check https://github.com/snapshot-labs/sx.js/pull/115 as finalizing and executing proposal isn't part of the UI.
There seems to be something wrong with Vite setup after previous PRs, if you have issues opening the app you can copy `dist` instead of linking.
=> feat: compute ethRelayer execution

src/stores/proposals.ts, src/views/Space/Overview.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/353
Summary has its own logic how it's fetched so using main proposals as substitute for summary won't work as we won't have enough old proposals in the end. Trying to handle it somehow will be mess so I'm just separating them into two different properties.
- Go to http://127.0.0.1:8080/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposals
- Click Overview - it fetches as expected.
- Go back to Proposals - no duplicates (but doesn't fetch again).
- Click on Proposal from Summary/Proposals page - it doesn't refetch it.
=> fix: separate summary from main proposals

package.json, src/networks/starknet/actions.ts, yarn.lock
This PR bumps sx.js to this version: https://github.com/snapshot-labs/sx.js/pull/115
With that PR L1 destination address is updated so it works with goerli2.
Once that PR is merged I will update this PR to use npm version.
- Link sx.js to https://github.com/snapshot-labs/sx.js/pull/115
- Follow that PRs test plan.
=> chore: bump sx.js

src/components/Block/InfiniteScroller.vue, src/components/ProposalsList.vue, src/networks/starknet/api.ts, src/networks/starknet/queries.ts, src/stores/proposals.ts, src/views/Space/Proposals.vue
- Add `InfiniteScroller` component.
- Split `fetchAll` into `fetch` and `fetchMore` (a bit more code repeating, but putting all logic for both first call and more fetches in single function was making it a bit hard to understand).
- Convert proposals page to be infinite scrollable.
- Go to http://127.0.0.1:8080/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposals
- You can fetch whole list.
- Nothing else breaks.
=> feat: add infinite scroll to proposals

src/components/Block/InfiniteScroller.vue, src/components/Sidebar.vue, src/networks/starknet/api.ts, src/networks/starknet/queries.ts, src/stores/proposals.ts, src/stores/spaces.ts, src/views/Home.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/357
This PR adds infinite scroll to spaces on front page. It's disabled by default and triggers only when user presses "Load more" button, similar as on Snapshot.org
- No Button to "Load more" is visible.
- Change `SPACES_LIMIT` to 2.
- Go to homepage
- Button shows up, click it.
- New elements are loaded.
=> feat: add infinite scroll to spaces

src/App.vue, src/components/Nav.vue, src/components/Topnav.vue, src/router.ts, src/stores/ui.ts, src/views/Space.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/365
With our quite complex structure of sidebars (we have 3 fixed elements, that all need to be shifted in different way) it ended up with a bit ugly set up as each of those has to contain logic for how it's going to be shifted (can't be shifted at parent level as transform modifies origin and `fixed` positioning no longer works.
Overall it should work as it used to on bigger screen (with exception of sidebar and nav now collapsing at once to have consistent experience). When on smaller screens those are assumptions that should be the case:
- You can use backdrop to dismiss.
- When picking element from sidebars sidebar closes.
- With sidebar open page is not scrollable.
- Content is translated right, instead of shrunk down (so it should …
=> feat: add responsive sidebar

src/views/Create.vue
Create page navbar currently displays incorrectly at certain breakpoints. This PR adjust this behavior.
- Go to Create page
- Resize it from small to big, no weird stuff happens.
Before:
After:
This screen doesn't show menu icon at the moment. I don't think it's a big deal, because you have back button still, but if we want to make menu accessible on this screen as well we might need to consider some design changes (right now showing both hamburger icon and back icon will look weird I think).
=> fix: update Create page navbar position

src/components/Topnav.vue
There were some issues with topnav 1) being translated on large screen causing button on right side to be off-screen 2) misaligned if sidebar was opened and the window was later resized to large size.
After:
https://user-images.githubusercontent.com/1968722/211562700-582e59cb-88e1-4588-9cfc-8d474e776496.mp4
Before:
https://user-images.githubusercontent.com/1968722/211562901-239c3909-0ec3-4756-9896-aa7d51505ba0.mp4
=> fix: properly display topnav in space screen

src/components/Block/Actions.vue, src/views/Proposal.vue
Just the UI for actions UI.
Towards https://github.com/snapshot-labs/sx-ui/issues/366
Proposal with quorum met has actions UI:
http://127.0.0.1:8080/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposal/38
Proposal without quorum met doesn't:
http://127.0.0.1:8080/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposal/44
=> feat: add proposal actions UI

package.json, src/components/Block/Actions.vue, src/composables/useActions.ts, src/helpers/constants.ts, src/networks/starknet/actions.ts, src/networks/starknet/api.ts, src/networks/starknet/queries.ts, src/types.ts, src/views/Proposal.vue, yarn.lock
Depends on https://github.com/snapshot-labs/sx-ui/pull/370
Towards https://github.com/snapshot-labs/sx-ui/issues/366
This PR makes finalize proposal and Zodiac actions (receive proposal + execute transactions) functional (you still need to update hardcoded proposalIndex as it's impossible to compute it).
- Create proposal with execution, vote for it until quorum is met.
- Click **Finalize proposal** button.
- **Wait for your transaction to arrive to become RECEIVED_ON_L1 (takes around an hour).**
- Once it has arrived update proposalIndex [here](https://github.com/snapshot-labs/sx-ui/blob/bdf8f2d8d65d17400c5a7495418590cade088e20/src/networks/starknet/actions.ts#L107-L108). It will be `proposalIndex - 1` from there: https://goerli.etherscan.io/address/0x196F0548E3140D2C7f6532a206dd54FbC1223 …
=> feat: add finalize and Zodiac actions

src/helpers/argentx.ts
ArgentX wasn't working for me. On first connect nothing would happen, on second attempt it might work. Looks like it's because we don't actually call `connect`, but deprecated `getStarknet()`.
- Connect with ArgentX.
- It works.
=> fix: properly connect with ArgentX

src/components/Modal/Drafts.vue, src/composables/useEditor.ts
Currently we show drafts from all spaces, but if you try to open draft from different space it won't work (data won't be loaded).
We have two ways of fixing this:
- Show all drafts in any space, just navigate to different space when selected - I started with this solution initially, but thought it will be confusing to suddenly end up in different space. I think it makes sense that drafts are space-scoped.
- Only show drafts from current space (this PR does that)
- Remove all drafts
- Go to A space, create a draft
- Go to B space, no drafts in drafts modal, create some draft in space B.
- Go back to A space, you can only see draft created for space A, space B's drafts are not visible.
=> fix: only show drafts from same space

.github/workflows/test.yml, package.json, src/helpers/utils.ts, src/networks/starknet/index.ts, src/views/Proposal.vue, src/views/Space/Treasury.vue, tsconfig.json, yarn.lock
Vite uses rollup/esbuild that don't actually typecheck the codebase, only transpile, meaning all type errors will go unnoticed. This adds new step with `vue-tsc` to run typechecks on builds and tests.
=> build: add typecheck step

src/components/Modal/PendingTransactions.vue, src/networks/evm/index.ts, src/networks/starknet/index.ts, src/networks/types.ts, src/views/Space/Settings.vue
This PR adds explorer URL from network for Space settigns page.
There is old `explorerUrl` still being used, but this will need some refactoring to improve network -> networkID mapping so leaving it out for now.
=> feat: use networks explorer url in Settings

src/components/Block/StrategiesConfig.vue, src/components/Modal/EditStrategy.vue, src/composables/useActions.ts, src/networks/evm/constants.ts, src/networks/starknet/constants.ts, src/networks/types.ts, src/views/Create.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/407
This PR adds strategy editor to create space page. Available strategies are defined per network and can specify if additional params are required.
Currently available strategies are displayed inline, to save some space.
It looks super busy in current form, but should be solved when we split creator into multiple steps.
- Sign in with ArgentX.
- Go to space creator.
- Create some spaces, play with editor.
=> feat: add strategies editor

src/App.vue, src/components/Label.vue, src/components/ProposalsList.vue, src/views/Space/Settings.vue, src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/418
- added sticky prop, without default state
- removed overflow-hidden from App wrapper div, cos sticky wont work with it [source](https://www.designcise.com/web/tutorial/how-to-fix-issues-with-css-position-sticky-not-working)
=> feat: add sticky prop to Label

src/stores/proposals.ts, src/stores/spaces.ts, src/views/Space/Proposals.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/435
This PR separates data stored in store into two properties:
- `entitiesIdsList` - array of IDs of entities list on UI (list of spaces, list of proposals)
- `entities` - map of IDs -> Entity that is used when rendering lists of rendering single entity (outside of a list).
This solves few issues:
- Potential race conditions when fetching results and single entity at the same time (eg. proposal might be added twice in the list if we fetch single proposal and proposal list).
- Already fetched single entity might disappear if we fetch list later.
=> refactor: separate data from lists in spaces/proposals

src/router.ts, src/stores/spaces.ts, src/views/Explore.vue, src/views/Home.vue, src/views/Space/Overview.vue, src/views/User.vue
This PR move the list of space to a new page "Explore". This also remove the pagination for spaces to load all of them at once, this avoid the issue of item count being inconsistent cuz we loading data from 2 different sources.
=> feat: move space list to explore page

src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/420
- when nfts tab is selected we use SendToken modal
- when tokens tab is selected we use SendNFT modal
=> feat: send NFT from treasury page

src/components/Topnav.vue, src/main.ts
Fixes #411 
This PR prevent usage of SX within an iframe, this is to avoid clickjacking.
=> fix: prevent iframe

src/components/Block/SpaceFormProfile.vue, src/components/Modal/EditSpace.vue, src/components/S/IObject.vue, src/components/S/ISelect.vue, src/components/Ui/Modal.vue, src/composables/useActions.ts, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts, src/helpers/validation.ts, src/networks/common/graphqlApi/queries.ts, src/types.ts, src/views/Create.vue, src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/409
Closes: https://github.com/snapshot-labs/sx-ui/issues/413
This PR adds social urls and treasury address to space profile editor.
**Currently treasury address in execution/treasury page is still hardcoded as we don't support Starknet there. Can be solved in other PR.**
- Use local deployment from https://github.com/snapshot-labs/sx-api/pull/173 or wait for it to be merged.
- Create space/edit space.
- Overview shows correct profile icons.
=> feat: add social urls and treasury address to space profile

src/networks/evm/constants.ts
Closes https://github.com/snapshot-labs/sx-ui/issues/453
This PR disabled vanilla authenticator from supported list (no longer possible to vote and propose with it) and editor (no longer possible to create space with it). Still left it in UI, so in old spaces it will show up as Vanilla.
=> feat(evm): remove vanilla authenticator support

src/helpers/utils.ts
Changes:
- use `fromNow` instead of `toNow` to make it more natural (right now `future` uses `ago` and `past` uses `left`).
- add custom cases for now: for future use `in few seconds`, for past `just now`.
=> fix: do not add ago to now time

src/networks/evm/actions.ts, src/views/Space/Proposals.vue
We should only convert `Date.now()`, `snapshot` timestamp is already in proper format.
- Go to proposal before you had delegated funds in space with CompToken strategy, you have 0 VP.
- Go to proposal after you had funds delegated, you have more VP.
https://user-images.githubusercontent.com/1968722/222683649-b6cb99b4-9f92-4cd4-b8b1-71308f095218.mp4
=> fix(evm): only convert Date.now() timestamp for VP calculation

src/components/Block/ExecutionEditable.vue, src/components/Block/TokenPicker.vue, src/components/ExecutionButton.vue, src/components/Modal/SendToken.vue, src/components/Nav.vue, src/composables/useTreasury.ts, src/helpers/space.json, src/helpers/utils.ts, src/views/Editor.vue, src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/465
This PR makes use of real treasury address (from metadata) to be displayed on UI: on treasury page and proposal creator.
- Go to space without treasury: http://localhost:8080/#/gor:0x232214209dcbb0328d0ac28d9a85efe4be8dcd7f
- Treasury tab is missing, when creating proposal SendToken/NFT modals are disabled.
- Go to space without treasury: http://localhost:8080/#/gor:0xb3782e21cedaf9183da9c472f810cc2fd337c6a2
- Treasury tab is there, when creating proposal SendToken/NFT modals are enabled.
=> feat: use real treasury

src/components/Results.vue, src/networks/common/graphqlApi/queries.ts, src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/473
Closes: https://github.com/snapshot-labs/sx-ui/issues/487
Display Results centered when displaying just the bar.
Changes:
- fetch quorum in proposal summary (bar was not displaying on Overview page).
- add `withDetails` prop to make `width` prop simpler
- center bar if `!withDetails`.
- Go to overview/proposals page, results bar is centered vertically there.
- Go to proposal page, results bar displays as it used to.
=> fix: display Results centered

src/components/ProposalsList.vue, src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/488
We will now display message if there are no tokens or NFTs in treasury.
=> feat: add empty-case for Treasury tokens/nfts

src/components/Modal/Transaction.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/451
- Go to create proposal page, click Contract call
- Click contact picker icon
- Confirm button is not displayed while contact picker is active.
=> fix: hide confirm button when picking contact in ModalTransaction

src/components/Results.vue
It's actually optional, but type was set as required, causing it to throw warnings.
=> fix: mark withDetails as optional

src/components/Proposal.vue, src/components/Vote.vue, src/networks/common/graphqlApi/index.ts, src/types.ts
We should prevent voting during voting delay period.
Closes: https://github.com/snapshot-labs/sx-ui/issues/498
- Create proposal on http://localhost:8080/#/gor:0xff0a04a1e441903f3f5631cfaf6c024cd923a47f
- You can't vote on it right away.
=> feat: prevent voting before voting delay ended

src/App.vue, src/components/Notifications.vue, src/components/Ui/Alert.vue, src/composables/useActions.ts, src/stores/ui.ts, src/types.ts, src/views/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/477
This PR adds generic UI errors to actions. They are the same for every action, but should be okay for now, at least you see when something failed.
- Add throw in some action in `useActions`.
- Try this action.
- Generic message appears.
=> feat: add generic UI errors for actions

package.json, src/components/Results.vue, src/components/S/IObject.vue, src/composables/useActions.ts, src/networks/common/graphqlApi/queries.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/starknet/actions.ts, src/networks/types.ts, src/types.ts, src/views/Proposal.vue, src/views/Space/Proposals.vue, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/469
- pass StrategyConfig to network actions
- set decimals on deploy
- interpret voting strategy metadata as decimals
- Create space with voting strategy, editor asks you to provide decimals
- Go to space with decimals (http://localhost:8080/#/gor:0xb2df4a0562d757df00fbc2bb3701041d05b4d757/proposals)
- It formats VP correctly.
=> feat: format voting power based on decimals

src/composables/useBalances.ts, src/composables/useNfts.ts
Currently NFTs and balances are global, meaning that switching from one space to another you will see old results.
- Go to one space (Decimals 16 + 18) -> Treasury -> NFTs.
- **Without refreshing**.
- Go to different space (Or-Land) -> Treasury -> NFTs.
- NFTs and balances were loading initially, you didn't see values from different space.
=> fix: keep balances/nfts state inside of composable

package.json, src/components/Block/SpaceFormStrategies.vue, src/components/Block/SpaceFormVoting.vue, src/composables/useActions.ts, src/helpers/utils.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/evm/helpers.ts, src/networks/evm/index.ts, src/networks/starknet/actions.ts, src/networks/starknet/constants.ts, src/networks/starknet/index.ts, src/networks/types.ts, src/views/Create.vue, src/views/Proposal.vue, src/views/Space/Settings.vue, yarn.lock
This PR updates code to work with latest contracts.
Missing functionality (will be added in next PRs, too many changes in this one already):
- No proper proposal validation support (you can only create spaces with vanilla validation, editor checks against proposal threshold that is hardcoded to 0 at API).
- Users can't pick execution strategy if there are multiple
- ~There is no vanilla execution strategy right now (needs to be deployed and some changes are needed on sx-subgraph).~ won't be used
I tested EthSig, Vanilla voting, CompVoting, AvatarExecution.
- Create your own space (you need to use avatar execution, you will only need to enableModule through Gnosis to enable your execution strategy, no other configuration needed).
- Propose
- Vote
- Execute
=> feat: add v0.4.0 contracts support

src/networks/evm/provider.ts
Using StaticJsonRpcProvider avoid querying `eth_chainId` before each `eth_call`
Here is an example on proposals page:
Before:
After:
=> chore: use StaticJsonRpcProvider

src/components/Label.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/506
Sticky is [bugy](https://twitter.com/youyuxi/status/1436026679059787781?lang=en) and not following screen exactly, which can cause some gaps.
Using workaround to shift it further up to avoid it.
=> fix: shift sticky to avoid gap

package.json, src/components/Block/SpaceFormStrategies.vue, src/components/Block/SpaceFormValidation.vue, src/components/Block/StrategiesConfigurator.vue, src/networks/evm/constants.ts, src/networks/types.ts, src/views/Create.vue
This PR adds simple UI for configuring Proposal validation for space.
After picking proposal validation you will need to configure it (in case of Voting Power Proposal Validation), by configuring voting power strategies that will be used for it.
**This PR doesn't validate proposal threshold correctly on editor page yet, will be added once sx-subgraph indexes those.**
- Create space with proposal validation
- Propose **This will only work if your voting strategies for voting are the same for proposal validation, if not check below how to hard code it.**
Override strategies here to match your (indexes has to be correct, same as when deployed):
https://github.com/snapshot-labs/sx-ui/blob/752d0027739e2c64d81c2c5dd2d79162aba6818a/src/networks/evm/actions.ts#L128
```js
strategies: [
{
index: 0, …
```
=> feat: add Proposal validation to create space form

src/networks/starknet/constants.ts
Change SX-API URL from https://testnet-api-1.snapshotx.xyz to https://api-1.snapshotx.xyz to match with UI.
=> chore: change sx-api URL

src/components/Modal/EditSpace.vue
Currently when opening edit space modal for space without treasury configured it will show wallet address field, even though it shouldn't do that.
That's because we are defaulting to '' and when decoding we might put undefined values into them as well.
This PR changes those fields to default to null.
- Go to space you control without treasury (create one or edit existing one if you don't have one).
- Click on edit space button.
- Treasury address field is invisible when No treasury is selected.
=> fix: default to null for wallet in edit space modal

src/components/Block/Actions.vue, src/networks/common/graphqlApi/queries.ts, src/types.ts
Depends on https://github.com/snapshot-labs/sx-ui/pull/524
Closes: https://github.com/snapshot-labs/sx-ui/issues/529
- Create and execute proposal (for timelock you will need to wait for "Execute queued proposal" button).
- Or check existing: http://localhost:8080/#/gor:0x818287662201bea70095bccc397b4ed69c142349/proposal/3
- Refresh page, it links to execution tx (the one that moved funds).
=> feat: link to execution transaction on Proposal page

src/components/VotingPowerIndicator.vue, src/helpers/utils.ts, src/views/Space/Treasury.vue
This PR adds `_c` helper for currency formatting, that specifies maximum number of decimal digits and displays `~0` in case number would is too small.
Closes: https://github.com/snapshot-labs/sx-ui/issues/528
- Set your VP to small amount (`1n`) here: https://github.com/snapshot-labs/sx-ui/blob/2753c894aa2065e50f9430833f0ac3a743d065b9/src/components/VotingPowerIndicator.vue#L37
- It displays as ~0.
=> feat: add _c helper for formatting currencies

src/components/Block/SpaceFormProfile.vue, src/components/Modal/EditSpace.vue, src/components/Modal/VotingPower.vue, src/components/VotingPowerIndicator.vue, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts, src/networks/common/graphqlApi/queries.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/starknet/actions.ts, src/networks/types.ts, src/types.ts, src/views/Create.vue, src/views/Proposal.vue, src/views/Space/Proposals.vue
This PR adds symbols for voting power strategies and global voting power symbol (for space).
Closes: https://github.com/snapshot-labs/sx-ui/issues/501
- Create space with custom symbol and with voting strategies that have their own symbol too.
- Go to Proposals page, you can see proper units used.
=> feat: add voting power symbols

src/components/Block/CreationConfirmation.vue, src/composables/useActions.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/starknet/actions.ts, src/networks/types.ts, src/views/Create.vue, src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/452
This PR adds extra screen in editor that shows progress of deployment of the space.
Changes:
- Now deploying dependencies (currently execution strategies) has visual feedback.
- UI waits for previous transaction to confirm, in case they fail.
- You can access transaction link for each step.
- Actual controller from form is used for new space, currently it was hardcoded to person singing the transaction.
=> feat: add confirmation screen when deploying space

src/components/Proposal.vue, src/router.ts, src/views/Proposal.vue
This reverts commit 3360a6bc763b3949973161ae4dd3438b80cc6fe6.
Closes: #492
This PR reverts https://github.com/snapshot-labs/sx-ui/pull/437 that introduced lots of issues related to sidebar visibility, that ended up being total mess to handle later.
@j0hnfl0w if you want you can resubmit https://github.com/snapshot-labs/sx-ui/pull/437, paying attention not to cause any regressions.
=> Revert "feat: refactor routes to handle 404 errors"

src/networks/common/graphqlApi/queries.ts, src/types.ts, src/views/Proposal.vue
We were expecting old format for decimals on Proposal page.
- Go to http://localhost:8080/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780/proposal/6
- Results have correct values of VP.
=> fix: use parsed decimals on Proposal page

src/components/Nav.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/565
=> fix: use globe icon for overview tab

src/components/Ui/Tooltip.vue, src/views/Space/Overview.vue, src/views/Space/Proposals.vue, src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/575
@bonustrack currently tooltips blend into Space background because they use the same color. Do you want to use some border on tooltips to prevent it?
- Check space header buttons, all should have tooltips.
=> feat: add header buttons tooltips

src/components/Block/ExecutionEditable.vue, src/composables/useTreasury.ts, src/views/Space/Treasury.vue
Current hook usage can lose reactivity, for example refreshing editor page will result in treasury not being found (buttons will be disabled) because space prop is loaded later.
This PR fixes it by making sure we are passing reactive value.
- Go to http://localhost:8080/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780/create
- Refresh page
- Execution buttons are all enabled
=> fix: keep reactivity for space in useTreasury

src/components/Topnav.vue, src/components/Ui/Tooltip.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/579
- In create space form Topnav should always be on top
- In proposals list buttons shouldn't cover sticky titles.
- Tooltip should be in front of Topnav (@bonustrack is this what we want? this was previous behaviour)
=> fix: prevent elements overlapping

src/components/Preview.vue
We have no icon so it crashes.
Closes: https://github.com/snapshot-labs/sx-ui/issues/587
=> fix: handle previews without icons

src/components/Block/ExecutionEditable.vue, src/components/Modal/SendToken.vue, src/composables/useActions.ts, src/composables/useEditor.ts, src/networks/evm/actions.ts, src/networks/evm/helpers.ts, src/networks/evm/index.ts, src/networks/starknet/actions.ts, src/networks/starknet/index.ts, src/networks/types.ts, src/types.ts, src/views/Editor.vue, src/views/Space/Treasury.vue
Depends on https://github.com/snapshot-labs/sx-ui/pull/552
Added field to make it possible to pick from different voting strategies that are configured for a space.
- Create space with multiple execution strategies, or use this one.
- You can select execution strategy when creating a proposal.
=> feat: add selection of execution strategy at proposal creation time

src/networks/evm/actions.ts, src/networks/evm/constants.ts
Currently ozVotes strategies do not show connected in VP modal, this can be added with simple fix.
- Go to http://localhost:8080/#/gor:0x90ccccd7667a8f67404c2f6fe3124ced1bb91237/proposals
- Click VP.
- Token address is shown in OZ votes voting strategy.
=> feat: display ozVotes token in modal

src/networks/evm/constants.ts
When creating metadata for new vanilla strategies we should set decimals to 0.
Closes: https://github.com/snapshot-labs/sx-ui/issues/603
=> fix: set Vanilla decimals to 0 in metadata

src/components/Label.vue, src/components/Ui/Tooltip.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/610
- Tooltips for vote buttons appear at correct position.
- Nothing breaks.
=> fix: use relative to set position of Tooltip

src/components/PendingTransactionsIndicator.vue
- Do some action (vote/create proposal).
- Hover over pending indicator (and keep it until indicator disappears).
- Tooltip's arrow is pointing to the center of the button.
- Once indicator disappears tooltip does too.
=> fix: move attrs and condition to Tooltip for indicator button

src/helpers/etherscan.ts
Regression from: https://github.com/snapshot-labs/sx-ui/pull/563
- Go to create proposal page.
- Create contract call execution with contract address of `0x3587b2F7E0E2D6166d6C14230e7Fe160252B0ba4`.
- It fetched ABI properly.
=> fix: parse fetched ABI

src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/534
This PR adds user friendly form messages.
1. Tries to use default message if it's not format error message.
2. If it's format error message use custom messages per type.
3. If it's format error message we don't have custom message for we show generic `Invalid format.` message as otherwise format isn't great (`must have format "ethValue"`).
Check some forms trying to break them that you know have validation working.
=> feat: add user friendly form errors

package.json, src/components/Block/SpaceFormController.vue, src/components/Block/SpaceFormProfile.vue, src/components/Modal/SendNft.vue, src/components/Modal/SendToken.vue, src/components/S/INumber.vue, src/components/Ui/Editable.vue, src/helpers/validation.ts, src/networks/evm/constants.ts, src/views/Editor.vue, src/views/Space/Settings.vue, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/606
This PR adds missing form validation:
- URL validation for discussion and website URL
- address validation for send token/NFT recipient and controller
- integer validation for quorum/timelock delay
It also required adding extra `skipEmptyOptionalFields` option to `validateForm` so we can decide what happens if we pass empty value for optional field, in most cases it might make sense to make it valid, which can be achieved with this option.
- Play with website URL, executions arguments and controller in create space form.
- Play with recipients in proposal execution modals and discussion URL.
=> feat: add missing form validation

src/composables/useActions.ts, src/networks/evm/actions.ts, src/networks/starknet/actions.ts, src/networks/types.ts, src/views/Create.vue, src/views/Editor.vue, src/views/Proposal.vue
This PR enables option to create spaces with no execution strategies and proposals without execution.
Closes: https://github.com/snapshot-labs/sx-ui/issues/621
- Deploy space with no execution strategies.
- Create proposal with no execution (in space with no executions).
- Create proposal with no execution (in space with executions).
- Create proposal with execution (in space with executions).
- Edit proposal above to remove that execution (should disappear, quorum will remain as it needs sx-subgraph update).
=> feat: allow proposals without execution

src/views/Space/Overview.vue, src/views/User.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/609
On mobile scrolling with overscroll might result in inaccurate final position (it's overscrolled at rest by subpixel margin) causing background to be visible where it should be covered entirely by topnav.
This PR only affects Cover because it's the only thing that is currently impacted. If we find it happening in other places we could change app's margin from 72px to 71px to compensate.,
=> fix: offset cover photo 1px up to handle overscroll bug

src/components/Block/SpaceFormProfile.vue, src/components/Block/StrategiesConfigurator.vue, src/components/Modal/EditSpace.vue, src/components/Nav.vue, src/composables/useDelegates.ts, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts, src/networks/common/graphqlApi/queries.ts, src/router.ts, src/types.ts, src/views/Create.vue, src/views/Space/Delegates.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/566
This PR adds adds delegates page that can be added to the space by configuring API url.
- Create new space or edit existing space profile to add delegation API URL (for example `https://api.thegraph.com/subgraphs/name/arr00/uniswap-governance-v2`).
- Go to space page.
- Go to Delegates page.
=> feat: add delegates page

src/components/Modal/Transaction.vue, src/helpers/ens.ts, src/helpers/provider.ts, src/networks/evm/index.ts, src/networks/evm/provider.ts
Closes #623
Currently we use two different StaticJsonRpcProviders that causes seperate eth_chanId requests. We can reuse single instance to avoid this.
=> refactor: use getProvider for evm network

src/App.vue, src/components/Modal/Drafts.vue, src/composables/useEditor.ts, src/composables/useRouteParser.ts, src/views/Editor.vue
Currently Editor doesn't work with changing routes as it handles some set up at mount time only.
This PR makes this component work with dynamic routes that makes it possible for it to be reused across rerenders instead of being unmounted and remounted as currently (we do this by setting key on router component), but it's wasteful. We should instead make our views handle those changes properly:
- https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation
This commit only handles Editor, but there are other views that have the same issue (but are easier to refactor), so will be updated separately.
- Play with editor, nothing should be broken.
=> refactor: make Editor respond to route changes

src/App.vue, src/views/Proposal.vue, src/views/Space.vue, src/views/User.vue
Depends on https://github.com/snapshot-labs/sx-ui/pull/634
This is continuation of Editor refactor, this time removing static handling of route params in other components.
With those changes we can now remove workaround for :key on router to force remounts and instead can reuse when routes change.
- Play with the app, nothing should break.
=> refactor: handle route params with reactivity

src/components/Modal/Transaction.vue, src/components/S/IBoolean.vue, src/components/S/INumber.vue, src/components/S/ISelect.vue, src/components/S/IString.vue, src/components/S/IText.vue, src/helpers/utils.ts, src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/639
This PR disabled Confirm button when transaction is invalid:
1. contract address is invalid
2. ABI is not defined (not found or user input doesn't work)
3. method values are invalid
Had to make some adjustments to make it work:
1. Update dirty flag on inputs when value changes from the outside.
2. Make `abiToDefinition` put all inputs to required property.
- Go to create proposal page, select execution -> Transaction.
- Input address that is not contract, error message is shown, button is disabled.
- Input address that is a contract, select method with inputs, do not file them in, button is disabled.
- Correct errors in the form, confirm button is enabled.
=> feat: disable Confirm button when transaction is invalid

src/components/VotingPowerIndicator.vue, src/views/Proposal.vue
This PR allows voting power modal to open when you click VP on proposal page.
- Go to proposal page.
- Click on VP amount.
- Modal opens.
=> feat: make VP indicator on proposal page open modal

src/components/Sidebar.vue, src/components/SpaceAvatar.vue, src/components/SpaceItem.vue, src/components/Stamp.vue, src/networks/common/graphqlApi/queries.ts, src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/640
Depends on: https://github.com/snapshot-labs/sx-ui/pull/645
This won't currently prevent old images from being used still as `cb` is ignored for AWS cache right now (pending https://github.com/snapshot-labs/stamp/pull/55)
You can test just the presence of `cb` parameter on space URLs (user URLs are not currently handled as there are plenty of places where we don't have access to real avatar URL to compute hash so for now it just handles spaces).
- Check different space image URLs.
- They have &cb parameter.
=> feat: add cache bust query parameter for space images

public/manifest.json, src/components/Ui/Alert.vue, src/composables/useActions.ts, src/main.ts, src/networks/evm/actions.ts, src/networks/evm/helpers.ts, src/types.ts
This makes it possible to use Safe with WalletConnect to propose/vote with spaces that have Ethereum transaction authenticator supported as well as manage space settings.
Closes: https://github.com/snapshot-labs/sx-ui/issues/605
Depends on https://github.com/snapshot-labs/sx-ui/pull/652
Depends on https://github.com/snapshot-labs/sx.js/pull/194
- Test different spaces:
- Ethereum signature only: http://localhost:8080/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780/settings
- Ethereum transaction only: http://localhost:8080/#/gor:0xfaa1e9cec71a2b56387aac1b368ef1a852891208
- Both: http://localhost:8080/#/gor:0x2b5e7ac0e76dcb41d3e506d58c9997d42d133e07
=> feat: add WalletConnect support with direct transactions

src/composables/useActions.ts, src/helpers/utils.ts
This PR will automatically add Linea to Metamask if it's not already added, without it it will fail with no feedback.
- Start with Metamask with no linea added (you can remove it in settings if it's not active).
- Try voting/proposing.
- You get prompted to add it.
- Try exiting at different stages of the flow (adding network, switching network, confirming transaction).
- Send transaction to vote/propose.
- Nothing breaks.
=> feat: add addEthereumChain call for Linea

src/components/Block/SpaceFormNetwork.vue
Regression from https://github.com/snapshot-labs/sx-ui/commit/ad37da57cfdb0f83ff96f8edff9e847c31811541 causing typecheck to fail.
=> chore: reduce null to undefined

src/components/Proposal.vue, src/components/Vote.vue, src/composables/useActions.ts, src/stores/ui.ts
This commit adds pendingVotes in state (it's lost on refresh), so after voting you can't vote for the same proposal again.
This is simple workaround to make UX better. In the future we probably should have better way to handle it where pending vote gets treated same as real ones with a way to handle cases where pending vote actually doesn't execute (transaction failure etc.)
=> feat: block voting again for same proposal

src/components/Modal/Votes.vue, src/networks/common/graphqlApi/index.ts, src/types.ts, src/views/Proposal.vue
Display ENS names for the votes modal.
**Test**
- Go to http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845/proposal/3
- Load votes
- ENS domains should appear
=> feat: resolve ENS name for votes

src/components/Proposal.vue, src/components/Vote.vue, src/composables/useActions.ts, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/networks/evm/actions.ts, src/networks/starknet/actions.ts, src/networks/types.ts, src/types.ts, src/views/Proposal.vue
This PR allows to cancel proposals.
Depends on: https://github.com/snapshot-labs/sx-subgraph/pull/27 (needs to be added to all subgraphs), see test plan how to test before it's deployed.
- Disable all networks but `gor`.
- Change `gor` apiUrl to https://api.studio.thegraph.com/query/41343/sekhmet-sx-goerli/version/latest.
- Create proposal.
- Go to that proposal as space owner.
- You can cancel it.
- Once cancelled it won't show up in proposal list.
=> feat: add proposal cancellation support

src/components/Markdown.vue
Currently it's not easy to see links on a proposal, this PR add an underline on links from Markdown components to make it more visible, this is the same approach used by Medium or Mirror.
**Test**
- Got to http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845/proposal/5
=> style: add underline on markdown links

src/stores/ui.ts
- Change txId to `0xe1d29d7207d7fb4b834e4f56c66554b101dfdb7d835809791c01c9193eec3c59` in addPendingTransaction.
- Do some action (Mana looks broken now so check something else).
- Refresh page after 5 minutes, pending transaction is cleared.
=> feat: clear pending transactions after 5 minutes

src/helpers/alchemy/index.ts, src/networks/evm/index.ts, src/networks/starknet/index.ts, src/networks/types.ts, src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/632
ETH redirects to treasury page itself.
- Go to here: http://localhost:8080/#/sep:0x8e7793c005bb37c7b7b47c1ae980dc6ddd2edbf5/treasury
- You can open tokens and NFTs by clicking them on explorers.
=> feat: link to token/NFTs from treasury

src/components/Block/SpaceFormProfile.vue, src/components/Modal/EditSpace.vue, src/components/Notifications.vue, src/components/S/IStampCover.vue, src/components/SpaceCover.vue, src/components/Stamp.vue, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/types.ts, src/views/Create.vue, src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/580
Closes: https://github.com/snapshot-labs/sx-ui/issues/658
Depends on: https://github.com/snapshot-labs/stamp/pull/56
Depends on: https://github.com/pulls
- Use local stamp from PR and change URL in Stamp.vue
- Change goerli API URL to https://api.studio.thegraph.com/query/41343/sekhmet-sx-goerli/version/latest
- Disable all other networks.
- You can see cover photo there.
- You can add cover photos to your own spaces.
We might want to lift size limit on pineapple too, some images will fail to upload now.
=> feat: add Space cover support

src/components/Block/SpaceFormVoting.vue, src/components/S/IDuration.vue, src/components/Ui/Editable.vue, src/style.scss, src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/545
This PR adds validation for min/max voting duration.
- When creating space it validates max isn't lower than min.
- When editing space it validates each value separately (because they are updated independently).
- Try setting wrong values when deploying space.
- Try setting wrong values when editing space.
=> feat: validate min max voting duration with each other

src/helpers/ens.ts
It seems that some addresses cause the call to revert, breaking logging in. For example calling get names with 0xaDa7E6d162C3Ff6f493Cc848f9FE1Bd74dD70A17 will throw.
This change will swallow errors and return empty object if this happens.
=> chore: handle getNames failure

src/views/Space/Overview.vue
overflow-hidden was added before that caused it to move to bottom position (to prevent tooltips from being partially cut off). Removing it restores old placement, and it doesn't seem to cause any other issues.
=> fix: display tooltips at top of overview buttons

src/composables/useMarkdownEditor.ts, src/views/Editor.vue
This PR adds toolbar buttons for adding heading/bold/italic and links. Heading/bold/italic use text as icons as heroicons doesn't have anything matching.
Closes: https://github.com/snapshot-labs/sx-ui/issues/699
- Go to editor and try using it.
=> feat: add markdown toolbar to editor

src/components/Modal/Timeline.vue, src/networks/evm/index.ts, src/stores/meta.ts
This PR fixes the time in timeline, it convert block number to timestamp using current block.
**Before**
**After**
=> fix: convert block to timestamp on timeline

src/App.vue, src/components/Block/ContactPicker.vue, src/components/Block/ExecutionEditable.vue, src/components/Modal/EditContact.vue, src/components/Modal/PendingTransactions.vue, src/components/Modal/Timeline.vue, src/components/Nav.vue, src/components/Notifications.vue, src/components/PendingTransactionsIndicator.vue, src/components/S/IStamp.vue, src/components/S/IStampCover.vue, src/components/Sidebar.vue, src/components/SpaceItem.vue, src/components/Topnav.vue, src/components/Vote.vue, src/composables/useActions.ts, src/composables/useMarkdownEditor.ts, src/stores/meta.ts, src/stores/proposals.ts, src/views/Editor.vue, src/views/Explore.vue, src/views/Proposal.vue, src/views/Settings.vue, src/views/Settings/Contacts.vue, src/views/Space.vue, src/views/Space/Overview.vue, src/views/Space/Proposals.vue, src/views/Space/SearchProposals.vue, src/views/User.vue, vite.config.ts
Closes #729 
This PR remove the global loading to get all networks current blocks and instead load current block for a single network when a space or a proposal is loaded. Also this add auto-import for the stores.
=> feat: load current block at space level

src/components/S/IDuration.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/725
Now error state won't be shown unless user interacted with input
=> feat: add dirty flag to IDuration

src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/720
- Create proposal with voting delay. (http://localhost:8080/#/sep:0xea4322cc9be9ae0c9400984209c858031b1c4438/proposal/3)
- Before voting starts no results are shown.
=> feat: hide results if voting hasn't started yet

src/components/Block/SpaceFormVoting.vue, src/composables/useActions.ts, src/stores/meta.ts, src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/750
This PR adds IDuration input for sx-evm voting delay and voting periods with blocks being estimated from duration.
- Deploy new EVM space.
- Go to deployed space settings, values are formatted as durations there.
- Try editing one of the settings, everything works as expected.
=> feat: use IDuration input for sx-evm with block estimations

package.json, src/components/Block/CreationConfirmation.vue, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/starknet/actions.ts, src/networks/starknet/constants.ts, src/types.ts, src/views/Editor.vue, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/622
This PR adds support for whitelist strategies with simplified UI (textarea where you put addresses in specified format), no custom UI as of now.
- Add Starknet/EVM whitelist strategy to space.
- Try propose/vote.
=> feat: add whitelist support with simplified UI

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
You can still create an issue without the template
These are the same templates we have on snapshot repo. You can test it there
=> Create ISSUE_TEMPLATE/BUG_REPORT.yml and ISSUE_TEMPLATE/FEATURE_REQUEST.yml

src/components/Notifications.vue, src/components/Ui/Alert.vue
Closes: #771
The issues was that somehow `w-fit` wasn't taking effect. Fixes it buy adding `!` and I also increased the gap to 16px. And fixed a typo
Preview:
1. Make action that triggers Notification
=> fix: Notification width

src/stores/proposals.ts, src/stores/spaces.ts, src/views/Proposal.vue, src/views/Space.vue
Because we made calling fetchBlock from global to on-demand there is risk that UI doesn't call it when it's needed (it happened in case of visiting space from explore page where it has space right away.
We avoid this problem by making requesting latest block responsibility of store actions (it won't fetch new block if it's already fetched).
Regression from: https://github.com/snapshot-labs/sx-ui/pull/730
Closes: https://github.com/snapshot-labs/sx-ui/issues/780
1. Go to http://localhost:8080/#/explore
2. Click on Shadow DAO
3. Proposals in overview page show as closed proposals.
=> fix: fetchBlock on loading proposals/spaces

src/components/ExecutionButton.vue, src/components/Modal/Votes.vue, src/components/NftPreview.vue, src/components/Proposal.vue, src/components/Stamp.vue, src/components/Ui/Modal.vue, src/components/Ui/Select.vue, src/helpers/utils.ts, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/networks/types.ts, src/router.ts, src/style.scss, src/types.ts, src/views/Proposal.vue, src/views/Proposal/Overview.vue, src/views/Proposal/Votes.vue, src/views/Space/Proposals.vue, tailwind.config.js
Closes: https://github.com/snapshot-labs/sx-ui/issues/724
Closes: https://github.com/snapshot-labs/sx-ui/issues/607
- Use different sorting/filters.
=> feat: add votes page

.env, package.json, src/networks/evm/actions.ts, src/networks/evm/index.ts, src/networks/index.ts, src/types.ts, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/770
This PR also enabled Ethereum mainnet as valid network so we can have proper "live" deployment.
1. Run `VITE_ENABLED_NETWORKS=eth yarn dev`
2. Only Mainnet spaces are available.
=> feat: allow to enable networks via env

src/composables/useActions.ts, src/composables/useWeb3.ts, src/stores/spaces.ts
Closes: https://github.com/snapshot-labs/pitches/issues/50
Tracks following events in Mixpanel:
- Connect wallet
- Create space
- Propose
- Vote
- Delegate
-  Favorite space
**Vercel fails because it tries to build stories that are worked on in other PR.**
1. Do any of the actions listed.
2. Events should be stored in Mixpanel (make sure adblocker doesn't block it for you).
=> feat: add basic Mixpanel events

package.json, src/networks/starknet/actions.ts, yarn.lock
Fixes two issues:
- Make merkle tree address lookup independent of paddings.
- Use validation strategy strategies metadata when proposing (it was fixed in PR that adds support for editing strategies, but never ported back to master).
- Create space with merkle whitelist strategy as validation strategy but not as voting strategy.
- Try proposing.
=> fix: make Starknet whitelist work again

.github/workflows/test.yml, README.md, package.json
Non-watch should be default variant. We want to run all test under same name under mono repo.
1. CI should pass.
=> chore: split test and test:watch

src/components/Block/SpaceFormNetwork.vue, src/networks/offchain/constants.ts, src/networks/offchain/index.ts
Filter out read only networks from create space form.
Also created constans for Snapshot network. 
1. Go to http://localhost:8080/#/create
2. Name space, go next.
3. Snapshot network is not visible.
=> fix: do not show read only networks on space creation form

src/components/Block/InfiniteScroller.vue, src/views/Proposal/Votes.vue
BlockInfiniteScroller used to wrap entire table but it wouldn't trigger endReached event because table itself didn't have any direct children added to it, so subtree property was added, but it caused different issue as now table's last element is always visible on screen (tbody) so it triggers endReached event all the time.
subtree property is not good solution and we should always wrap just the elements we want to load.
1. Go to http://localhost:8080/#/s:arbitrumfoundation.eth/proposal/0xc040de9c6a85dee5ca15de10691165bf5595245ffac922cbef61e45199522345/votes
2. Check for network requests - no requests being fired all the time.
3. Scroll down, it will fetch new votes as needed.
=> fix: remove subtree option for BlockInfiniteScroller

src/composables/useSpaces.ts
We don't fetch all networks for explore page (snapshot.org spaces are not fetched, but we have to keep previous networksMap entries so it doesn't get lost).
1. Go to http://localhost:8080/#/s:arbitrumfoundation.eth and favorite this space.
2. Go to http://localhost:8080/#/explore
3. Click on Arbitrum space from favorites list.
4. It loads.
=> fix: do not reset networksMap when fetching explore page

src/components/Link.vue, src/components/Markdown.vue, src/components/MarkdownEditor.vue, src/components/Proposal.vue, src/helpers/utils.ts, src/views/Editor.vue, src/views/Proposal.vue, src/views/Proposal/Overview.vue, src/views/Proposal/Votes.vue, src/views/Space/Treasury.vue
Closes #814 
Closes #818 
- Also this PR add markdown support for `backticks` you can try here: http://localhost:8080/#/s:balancer.eth/proposal/0x141051b2fe6f18e322539c0e54b2fb0d9872b6096f2c3fd71fa3bf27e5c7b8f8
- Increase width for proposal overview and editor to 660px
- Update loading layout on proposal votes page to be consistent with others loading
- Add border bottom on active tabs
- Truncate proposal preview title
=> style: enhance proposal view and tabs

src/composables/useDelegates.ts, src/composables/useWeb3.ts, src/helpers/ens.ts, src/helpers/stamp.ts, src/networks/common/graphqlApi/index.ts, src/networks/offchain/api/index.ts
Moving to Stamp RPC API to resolve names instead of doing requests on frontend, with this change we also resolve Lens and UnstoppableDomains names, and it includes a cache system. To test this change you can try delegates, votes page or others sections where we display ENS names.
=> feat: use Stamp API to resolve names

src/components/Ui/Select.vue, src/views/Space/Proposals.vue
A bit weird now, because we use `passed` for `closed` (so it actually includes passed + executed + rejected).
Closes: https://github.com/snapshot-labs/sx-ui/issues/817
1. Go to http://localhost:8080/#/sep:0xea4322cc9be9ae0c9400984209c858031b1c4438/proposals
=> feat: use ProposalStatusIcon for Proposal UiSelect

src/views/Proposal/Votes.vue, src/views/Space/Delegates.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/800
Votes already has loading indicators aligned to the left. Was it supposed to update votes modal instead? @bonustrack 
1. Check http://localhost:8080/#/sep:0xea4322cc9be9ae0c9400984209c858031b1c4438/delegates
2. Check http://localhost:8080/#/sep:0xea4322cc9be9ae0c9400984209c858031b1c4438/proposal/6/votes
=> feat: align loading and empty messages to left

src/networks/starknet/actions.ts
Now sx-starknet uses same enum as sx-evm so we need to convert it.
Closes: https://github.com/snapshot-labs/sx-ui/issues/826
1. Create proposal and vote to abstain.
2. It works and you should see it as abstained vote.
=> fix: convert choices to native format

package.json, src/components/Nav.vue, src/composables/useActions.ts, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/networks/common/helpers.ts, src/networks/evm/actions.ts, src/networks/evm/constants.ts, src/networks/offchain/api/index.ts, src/networks/starknet/actions.ts, src/networks/starknet/constants.ts, src/networks/types.ts, src/router.ts, src/types.ts, src/views/Space/EditSettings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/659
This PR adds ability to edit authenticators/votingStrategies/proposalValidationStrategy on spaces (EVM and Starknet).
- Deploy new space (to make sure it has all metadata created properly, old spaces didn't have proposal validation strategies metadata).
- Try editing it.
Temporary UI, but functional.
=> feat: add strategies editing

tailwind.config.js
Closes https://github.com/snapshot-labs/sx-ui/issues/755
Fix is related to https://github.com/tailwindlabs/tailwindcss/pull/8394
> Again this will be a breaking change in v4, but only for evil people who were writing code like hidden group-hover:block. Until then, everything will work the same, and you can opt-in to this if you want to start using it now.
So the problem is with the `group-hover` class and IOS devices don't support hover events, on the first click it assumes as `hover`
This change will disables on mobile devices but hovers should still work on desktops 
An alternate way is to handle click with JS
1. Open the explore page on IOS Safari
2. Click on any space
3. Before fix: It will take two clicks to go to space page
4. After fix: It will take one click to go to space page
5. …
=> fix: Disable hover on devices that don't support it

src/components/Block/Delegates.vue, src/components/Block/SpaceFormProfile.vue, src/components/Modal/Delegate.vue, src/components/Modal/DelegationConfig.vue, src/components/Modal/EditSpace.vue, src/components/Nav.vue, src/composables/useActions.ts, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts, src/networks/common/graphqlApi/index.ts, src/networks/common/graphqlApi/queries.ts, src/networks/common/graphqlApi/types.ts, src/networks/evm/actions.ts, src/networks/evm/index.ts, src/networks/offchain/api/index.ts, src/networks/types.ts, src/types.ts, src/views/Create.vue, src/views/Space/Delegates.vue
**Only Starknet was tested as of now.**
Closes: https://github.com/snapshot-labs/sx-ui/issues/833
Depends on https://github.com/snapshot-labs/sx-api/pull/205
Depends on https://github.com/snapshot-labs/sx-subgraph/pull/43
1. Run local sx-api.
2. Run sx-ui with sn-tn only: `VITE_ENABLED_NETWORKS=sn-tn yarn dev`.
3. Deploy new space with multiple delegations.
4. Edit that space delegations in edit space modal.
5. View delegations for space (**currently subgraph fails for some subgraphs because it's overloaded**).
=> feat: index multiple delegations

src/networks/evm/index.ts, src/networks/offchain/index.ts, src/networks/starknet/index.ts, src/networks/types.ts, src/stores/meta.ts
Arbitrum uses eth mainnet blocks for block.number.
Closes: https://github.com/snapshot-labs/sx-ui/issues/824
1. http://localhost:8080/#/arb1:0x2fb231a3ac7c40888d2e6773f5600851b0c20ce4/proposal/2
2. Timeline in modal and Ended time make sense.
=> fix: use eth mainnet blocks for current

package.json, yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/851
1. `VITE_ENABLED_NETWORKS=sn yarn dev`
2. Create space with evm slot value (you can use this contract `0x7421B0f131c32876c0eF305F9e4B2591bfbFF472`).
3. Try creating proposal and voting (once herodotus is processed).
Sample proposal http://localhost:8080/#/sn:0x01232584ed4f94aab39c1bedf295aff876ff30d5c9ecbcb395eaf47cd492d50c/proposal/1
=> feat: enable evm slot value on mainnet

src/App.vue, src/composables/useUserSkin.ts
Since https://github.com/snapshot-labs/sx-ui/pull/794 dark style is only applied within Vue tree, which won't apply to body itself.
This causes body to remain white when dark theme is used which can become visible during overscroll. This commit replaces two ways of setting dark theme (data-color-scheme and class) with just once (class) set to html document.
1. Go to UI, can switch between dark/light mode with no issues.
2. Run `yarn story:dev` - dark mode works there too.
=> fix: apply dark class to html tag

src/components/Proposal.vue, src/networks/common/helpers.ts, src/networks/evm/actions.ts, src/networks/starknet/actions.ts, src/types.ts, src/views/Proposal.vue
We used to use 1 | 2 | 3 for vote choice on UI (for, against, abstain). Which was inconsistent with sx.js (0 abstain, 1, for, 2 against).
It could lead to issues as those values are not really clear on the UI. This commit replaces 1 | 2 | 3 with 'for' | 'against' | 'abstain' that are converted to SDK values in single place. This makes UI code more readable as actions are easy to understand.
- You can still vote -> signed message (if using sig authenticator) uses correct choice.
=> refactor: replace choice magic numbers with string values

package.json, src/networks/starknet/constants.ts, src/views/Space/EditSettings.vue, yarn.lock
Closes: https://github.com/snapshot-labs/pitches/issues/74
1. Get some token and delegate it to yourself: https://sepolia.etherscan.io/address/0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4#readContract
2. Create new space (with EthSig/EthTx) using OZ Votes storage proof strategy (use above token, slot index 8).
3. Create new proposal.
4. Wait for it to be processed on Herodotus.
5. You can now see your voting power and vote (http://localhost:8080/#/sn-sep:0x07101663a830e0c821785f7537f570901d2a8bf1ed46f70aaacd73c4c7192cf8/proposal/1)
=> feat(starknet): add OZ Votes storage proof strategy support
