snapshot-labs/sx-ui

- src/components/Block/ExecutionEditable.vue
- src/components/Modal/SendNft.vue
- src/components/Modal/SendToken.vue
- src/components/Modal/Transaction.vue
- Go to http://localhost:8080/#/0x0625dc1290b6e936be5f1a3e963cf629326b1f4dfd5a56738dea98e1ad31b7f3/create
- No warnings should be visible in the console.
> fix: get rid of warnings in proposal page

- src/components/Modal/Drafts.vue
- src/composables/useEditor.ts
- src/views/Create/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/143
Adds Delete button for drafts.
- Can delete drafts.
- Can delete current draft (new draft will be generated).
> feat: add delete draft button

- src/components/Block/TokenPicker.vue
- src/components/Modal/SendToken.vue
- src/components/S/INumber.vue
- src/composables/useBalances.ts
- src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/142
Changes:
- extract `useBalances` composable
- update `INumber` component as there is no way to make it update from the outside (modalValue) is just the default value and turned it in more standard two-way bound input that accepts `value` and `@input`. This makes it compatible with `v-model` (which is not used here as we need to control value updates).
- add `TokenPicker`
- make amount/value inputs adjust based on the rate.
- Go to http://localhost:8080/#/0x0625dc1290b6e936be5f1a3e963cf629326b1f4dfd5a56738dea98e1ad31b7f3/create
- Type some amount, nothing happens.
- Pick some token.
- Value input has updated.
- Try using both inputs, they should be linked.
- If you delete all contents  from one input it's also deleted from other (so …
> feat: TokenPicker to SendToken modal

- src/components/Block/NftPicker.vue
- src/components/Modal/SendNft.vue
- src/components/NftPreview.vue
- src/composables/useNfts.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/153
Adds NFT picker to Send NFT modal.
**Note**: Sometimes Covalent is slow to fetch NFTs.
- Replace `loadNfts(spaces.pasta.wallets[0]);` with `loadNfts('0xfC00116B4049BBc8618847C74B44F0e103D571A3');` or other address you want to test with.
- You can pick, search and select NFTs.
- Preview shows up in the send NFT modal.
> feat: add NFT picker

- src/components/Block/TokenPicker.vue
- src/components/Modal/SendToken.vue
- src/composables/useBalances.ts
- src/helpers/constants.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/167
- Ethereum will be shown first in the list of assets in the picker
- Ethereum will be selected by default
> feat: prioritize and preselect Ethereum in picker

- .github/workflows/test.yml
- .gitignore
- package.json
- src/helpers/__tests__/__snapshots__/transactions.test.ts.snap
- src/helpers/__tests__/transactions.test.ts
- src/helpers/transactions.ts
- yarn.lock
- Added `vitest`.
- Set up Github CI.
- Added sample test.
> test: add tests setup

- src/components/Block/NftPicker.vue
- src/components/Block/TokenPicker.vue
- src/components/Modal/SendNft.vue
- src/components/Modal/SendToken.vue
Mostly changing spacing for search input and list of tokens, also change "Select token" to "Select NFT" on the Send NFT modal.
> Improve style for execution modals

- src/components/Block/ExecutionEditable.vue
- src/components/Modal/SendNft.vue
- src/composables/useActions.ts
- src/views/Create.vue
- src/views/Create/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/166
- Add some transactions to proposal.
- Refresh page, they are still there.
- Switch between different drafts, it restores transaction for given proposal.
> feat: store proposal transactions

- src/components/Modal/Drafts.vue
- src/composables/useEditor.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/206
- Do not store empty drafts.
- Do not show empty drafts in Drafts modal.
> feat: ignore empty drafts

- src/components/Block/Execution.vue
- src/components/Block/NftPicker.vue
- src/components/Block/TokenPicker.vue
Small improvements towars better TS coverage.
> refactor: use TS in all block components

- src/components/Modal/Drafts.vue
- src/composables/useEditor.ts
- src/helpers/utils.ts
- src/types.ts
- src/views/Create/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/219
- create two drafts
- modify draft at the bottom
- it moves to the top of the list
- remove all contents from draft
- it gets removed
> feat: sort proposals by update date

- src/components/Ui/Modal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/229
- Open some modal
- Press ESC
- It closes
> feat: close modal on Esc key

- package.json
- yarn.lock
sass-loader is webpack plugin.
> chore: remove sass-loader

- src/helpers/constants.ts
- Go to http://127.0.0.1:8080/#/0x0375bc9b4d236f961cbc5410213cdbf2de6dfe30f21b2c58bb4de3713d868383/settings
- Contracts are properly recognized
> feat: update auth/strategy/execution contracts

- src/types.ts
- src/views/Space/Settings.vue
Test with https://github.com/snapshot-labs/sx-api/pull/150
- Going to Space settings works.
> feat: support array authenticators/strategies/executors

- src/components/Modal/Votes.vue
- src/components/Proposal.vue
- src/helpers/queries.ts
- src/types.ts
- src/views/Proposal.vue
Test with: https://github.com/snapshot-labs/sx-api/pull/152
- Whole app should work as before.
> feat: support sx-api with subqueries

- src/components/Proposal.vue
- src/composables/useActions.ts
- src/views/Create.vue
- src/views/Proposal.vue
Depends on https://github.com/snapshot-labs/sx-ui/pull/320
- Create proposal.
- Vote on proposal.
> feat: use authenticator/strategies from API

- src/components/Results.vue
- src/helpers/queries.ts
- src/style.scss
- src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/326
Test against as Vanilla strategy gives super small scores as sx-api formats them as amounts.
> feat: adjust results using quorum

- src/App.vue
- src/components/Vote.vue
- src/composables/useAccount.ts
- src/views/Proposal.vue
- tsconfig.json
Shows user choice on Proposal page
Closes: https://github.com/snapshot-labs/sx-ui/issues/324
> feat: show user vote in Proposal page

- src/components/ProposalsList.vue
- src/components/Vote.vue
- src/helpers/queries.ts
- src/stores/proposals.ts
- src/types.ts
- src/views/Space/Overview.vue
- src/views/Space/Proposals.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/325
> feat: add Closed proposals section

- src/components/Link.vue
- src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/316
Depends on: https://github.com/snapshot-labs/sx-ui/pull/331
> feat: add NFTs to treasury

- src/components/Block/Execution.vue
- src/components/Block/ExecutionEditable.vue
- src/components/Transaction.vue
- src/types.ts
- src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/333
- Check this proposal: `#/0x04b7cff71219e275676e0ca23579f41b99dd1d1bd01adc7d7f1bc917d448e57d/proposal/8`
> feat: add execution to proposal page

- src/App.vue
- src/components/Container.vue
- src/components/Preview.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/336
> fix: prevent too-wide UI

- src/components/Block/TokenPicker.vue
- src/components/Modal/SendToken.vue
- src/views/Space/Treasury.vue
Depends on https://github.com/snapshot-labs/sx-ui/pull/339
Closes: https://github.com/snapshot-labs/sx-ui/issues/337
> fix: truncate Token name

- package.json
- src/composables/useActions.ts
- src/helpers/clients.ts
- src/helpers/constants.ts
- yarn.lock
This PR adds goerli2 support with latest deployment.
Use this mana instance: https://github.com/snapshot-labs/mana/pull/82
- Create proposal
- Vote
> chore: add goerli2 support

- src/views/Create.vue
- src/views/Create/Editor.vue
Currently pressing back button in browser at editor screen won't make you go back. Also deleting the draft doesn't make you go back to fresh editor and instead leaves you at current URL
- Go to editor through UI.
- Press back.
- You get back to space.
> fix: prevent getting stuck at editor

- .env
- src/components/Block/TokenPicker.vue
- src/components/Modal/SendToken.vue
- src/composables/useBalances.ts
- src/helpers/__tests__/transactions.test.ts
- src/helpers/alchemy/index.ts
- src/helpers/alchemy/types.ts
- src/helpers/space.json
- src/helpers/transactions.ts
- src/views/Space/Treasury.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/172
Moves fetching token balances to Covalent. Pricing data is missing (which was also missing on Goerli with Covalent). We will need to use CMC/CG to add pricing info.
- Check treasury page.
- Check Send Token token picker.
> feat: migrate balances to Alchemy

- src/components/Proposal.vue
- src/components/Ui/Loading.vue
- src/composables/useActions.ts
- src/views/Create.vue
- src/views/Proposal.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/374
This PR adds UI feedback when casting votes or creating proposals. Feedback is removed once we get txId back.
> feat: add pending state for votes/proposals

- src/components/Modal/EditSpace.vue
- src/components/S/IObject.vue
- src/components/S/IText.vue
- src/components/Ui/Loading.vue
- src/helpers/validation.ts
- src/views/Space/Overview.vue
Towards https://github.com/snapshot-labs/sx-ui/issues/378
This adds UI for editing space
> feat: add EditSpace UI

- package.json
- src/components/Modal/EditSpace.vue
- src/composables/useActions.ts
- src/composables/useWeb3.ts
- src/helpers/argentx.ts
- src/networks/evm/index.ts
- src/networks/starknet/actions.ts
- src/networks/starknet/index.ts
- src/networks/types.ts
- yarn.lock
Depends on https://github.com/snapshot-labs/sx.js/pull/128
Closes https://github.com/snapshot-labs/sx-ui/issues/378
This makes edit space functional for Starknet spaces
Sign in with ArgentX, edit space you control (you can use follow up PR to create new one if you need).
> feat(starknet): make edit space functional

- src/components/Block/ExecutionEditable.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/399
> fix: adapt execution handle color to skin

- src/components/Topnav.vue
- src/composables/useActions.ts
- src/networks/evm/actions.ts
- src/networks/evm/index.ts
- src/networks/starknet/actions.ts
- src/networks/starknet/index.ts
- src/networks/types.ts
- src/router.ts
- src/types.ts
- src/views/Create.vue
- src/views/Home.vue
Depends on https://github.com/snapshot-labs/sx-ui/pull/398
Depends on https://github.com/snapshot-labs/sx.js/pull/131
This adds very simplified UI to create Starknet spaces.
Sign in with ArgentX, click plus button in Topnav, fill the form and submit it.
> feat(starknet): add simplified deploy space form

- src/composables/useWeb3.ts
- src/helpers/utils.ts
- src/networks/evm/actions.ts
- src/networks/evm/index.ts
- src/networks/starknet/actions.ts
- src/networks/starknet/index.ts
- src/networks/types.ts
Closes https://github.com/snapshot-labs/sx-ui/issues/388
This PR will prompt user to change network in Metamask if incorrect is selected.
ArgentX doesn't support network changes.
- Do actions that requires singing via Metamask while having wrong network selected.
- Metamask prompts you to change network.
- If rejected it won't do the action.
- If accepted action will continue executing.
> feat: request network change

- src/networks/starknet/actions.ts
We currently allow user to use vanilla executor in space alone, but we hardcode zodiac executor when creating proposal.
This PR adds support for vanilla as well.
Closes: https://github.com/snapshot-labs/sx-ui/issues/432
- Create proposal on http://localhost:8080/#/sn-tn2:0x022a6667315cc87d7e92f994ac6b621a7a86f76f78442cf90155ae5a7fc27dc9
> feat: support vanilla executor

- src/composables/useActions.ts
- src/views/Editor.vue
Closes https://github.com/snapshot-labs/sx-ui/issues/442
- Without logging in go to proposal editor.
- Hit publish - it doesn't take you back.
- Submit proposal after logging in - it takes you back.
> fix: only go back on propose/deploy if succeeded

- src/networks/evm/actions.ts
- src/networks/evm/constants.ts
- src/views/Create.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/440
EVM deploy space editor (vanilla/ethTx authenticator, vanilla/compToken strategy, vanilla execution).
- Deploy space via form on EVM.
> feat(evm): implement deploy space for Ethereum in editor

- package.json
- src/components/Block/Actions.vue
- src/components/Results.vue
- src/components/Vote.vue
- src/composables/useActions.ts
- src/helpers/transactions.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/evm/actions.ts
- src/networks/evm/constants.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/types.ts
- src/views/Proposal.vue
- src/views/Space/Settings.vue
- yarn.lock
Depends on https://github.com/snapshot-labs/sx-ui/pull/444
Closes: https://github.com/snapshot-labs/sx-ui/issues/366
- Handle avatar execution
- Proposal-level quorum
- Deploy ethereum space updates (quorum at execution, you can deploy avatar execution, but it won't be functional until you manualy whitelist strategy on avatar and space on strategy).
- Executed state for proposal.
Lots of ugly stuff, hacked quickly for a demo. Plenty of stuff doesn't make sense now, because contracts might be dynamic.
> feat(evm): add quorum, execution

- src/helpers/utils.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/evm/actions.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/types.ts
- src/views/Proposal.vue
- src/views/Space/Proposals.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/433
Depends on: https://github.com/snapshot-labs/sx.js/pull/159
Depends on: https://github.com/snapshot-labs/sx-ui/pull/457
- Check voting power on different spaces.
> feat: display voting power

- src/components/Block/SpaceFormProfile.vue
- src/components/S/ISelect.vue
- src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/475
> feat: user friendly network name

- src/views/Explore.vue
It's now possible to favorite spaces on Explore page on hover.
Closes: https://github.com/snapshot-labs/sx-ui/issues/483
> feat: add toggle space favorite button on Explore page

- src/components/Block/NftPicker.vue
- src/views/Space/Treasury.vue
This PR changes NFTs grid to use consistent gaps around.
Closes: https://github.com/snapshot-labs/sx-ui/issues/493
> feat: consistent NFT grid gaps

- src/components/Ui/Alert.vue
- src/networks/evm/actions.ts
- src/networks/evm/index.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/types.ts
- src/views/Editor.vue
- src/views/Proposal.vue
- src/views/Space/Proposals.vue
- tailwind.config.js
Closes: https://github.com/snapshot-labs/sx-ui/issues/460
This PR adds check to proposal threshold on proposal editor.
- Try creating proposal here http://localhost:8080/#/gor:0xd9e572dfe8f188dc34dbc5adc5413ab695b684c5
- It should show error message for all accounts.
- Try creating proposal here http://localhost:8080/#/gor:0x71dc8ba1121d00e48d8fca1558895205845f1463
- It shouldn't show error
> feat: validate proposal threshold when creating a proposal

- src/components/Block/SpaceFormProfile.vue
- src/components/Modal/EditSpace.vue
- src/components/S/IObject.vue
- src/components/S/ISelect.vue
- src/helpers/validation.ts
- src/types.ts
- src/views/Create.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/480
- if walletNetwork === null we hide walletAddress input
- if walletNetwork !== null we must fill walletAddress
> feat: no-treasury in space create form

- src/components/Modal/VotingPower.vue
- src/components/VotingPowerIndicator.vue
- src/networks/evm/actions.ts
- src/networks/starknet/actions.ts
- src/networks/starknet/index.ts
- src/networks/types.ts
- src/views/Editor.vue
- src/views/Proposal.vue
- src/views/Space/Proposals.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/466
This PR adds Voting Power modal when clicking on VP button in Proposals list and Proposal page.
Modal will display voting power formatted using highest of decimals as well as voting strategy specific decimal as "units".
- Check http://localhost:8080/#/gor:0xff0a04a1e441903f3f5631cfaf6c024cd923a47f/proposals
> feat: add Voting Power modal

- src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/497
> fix: nft list item fixed width

- src/components/Nav.vue
- src/views/Space/Overview.vue
Add website icon on space overview:
http://localhost:8080/#/gor:0x7363dbc13ee217b7725559d53e7b3b089b82ea31
And reduce space between nav items.
> feat: add website icon

- src/networks/evm/helpers.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/510
- Try proposing on space with ethTx + ethSig (http://localhost:8080/#/gor:0xca65aae6f36f549942bfaa412f2c357f776eb9b4)
- It uses ethSig.
> feat: prefer ethSig authenticator

- src/components/Proposal.vue
- src/views/Proposal.vue
This adds titles to buttons that adds more context what they mean.
- Hover on vote buttons.
- You get tooltip.
> feat: add vote buttons titles

- src/components/Modal/Transaction.vue
Something changed and now, when you try to edit contract call it won't restore previous values (it will reload ABI).
This PR fixes that, by centralizing `ignoreFormUpdates` in single watcher, that handles both methods that depend on it (handleChangeMethod, handleChangeTo).
- Go to editor.
- Create contract call execution.
- Click edit icon.
- Your execution is restored in the modal.
> fix: restore contract modal contents

- src/components/Block/SpaceFormNetwork.vue
- src/networks/common/graphqlApi/queries.ts
- src/networks/evm/actions.ts
- src/networks/evm/constants.ts
- src/networks/evm/helpers.ts
- src/networks/index.ts
- src/networks/starknet/constants.ts
- src/networks/types.ts
- src/types.ts
- src/views/Editor.vue
- src/views/Space/Settings.vue
This PR adds real proposal validation at propose time (uses correct proposal validation strategies, and computes threshold requirement correctly). It also displays proposal validation in Settings.
**This PR disabled Starknet network, as we would need sx-api changes to make it work, we want to disable SN for now anyway, so keeping it this way for now.**
- Create space with proposal validation (you can use [this PR](https://github.com/snapshot-labs/sx-ui/pull/513))
- Propose works.
> feat: use real proposal validation

- src/networks/common/graphqlApi/queries.ts
We should show biggest votes first.
Closes: https://github.com/snapshot-labs/sx-ui/issues/532
- Check votes modal there: http://localhost:8080/#/gor:0xcebbae8f9e86f58532837e701650ffdba85738c6/proposal/3
> feat: sort proposal votes in modal

- src/components/Topnav.vue
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/types.ts
- src/router.ts
- src/views/Space/SearchProposals.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/507
This PR adds proposal search to space views.
- Go to some space: http://localhost:8080/#/gor:0xcebbae8f9e86f58532837e701650ffdba85738c6
- Search for different strings in proposal strings.
> feat: add proposal search

- src/components/Topnav.vue
Feedback from https://github.com/snapshot-labs/sx-ui/pull/542#issuecomment-1491596693
> chore: update search placeholder to "Search proposals"

- src/helpers/utils.ts
- src/views/Proposal.vue
- src/views/Space/Overview.vue
- src/views/Space/Treasury.vue
This PR adds sanitization to user generated URLs (or URLs that partially come from user input).
Closes: https://github.com/snapshot-labs/sx-ui/issues/523
> feat: sanitize user generated urls

- src/components/Nav.vue
- src/components/SpaceItem.vue
- src/composables/useSpaces.ts
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/types.ts
- src/router.ts
- src/stores/spaces.ts
- src/views/Explore.vue
- src/views/Settings.vue
- src/views/Settings/Spaces.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/467
> feat: add My spaces page

- src/views/Settings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/568
> fix: settings page unlogged

- src/components/S/IStamp.vue
- src/components/Sidebar.vue
- src/components/SpaceItem.vue
- src/views/Space/Overview.vue
To use new space-sx resolver for space avatar
Followup: https://github.com/snapshot-labs/stamp/pull/51#discussion_r1172556742
> feat: add space-sx resolver for stamp

- src/networks/evm/actions.ts
- src/networks/evm/helpers.ts
With this PR executing proposals on EVM will be done via mana.
Depends on: https://github.com/snapshot-labs/mana/pull/94
- Use local version of mana: https://github.com/snapshot-labs/mana/pull/94
- Create proposal with execution
- Execute it, it doesn't ask to send you the transaction, instead if does it via mana.
> feat: add mana-based execution of proposal

- src/components/Markdown.vue
- src/components/VotingPowerIndicator.vue
- src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/557
Depends on: https://github.com/snapshot-labs/sx-ui/pull/570
Currently no separate results/quorum section, pending some questions being answered.
Everything that was not included on the design was kept in main section (actions, execution etc.)
> feat: update Proposal layout

- package.json
- src/components/Ui/Editable.vue
- src/composables/useActions.ts
- src/networks/evm/actions.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/views/Space/Settings.vue
- yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/380
Depends on https://github.com/snapshot-labs/sx.js/pull/189
Allows to edit voting delay, min/max voting period and controller.
UI is likely temporary, as editing those values is only possible one by one currently, so single form doesn't really make sense.
But it works for now.
- Link https://github.com/snapshot-labs/sx.js/pull/189
- Go to settings of space you control.
- Change some settings.
> feat: add settings edit option

- src/views/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/581
> feat: change proposal body max length to 9600

- src/components/Ui/Modal.vue
- src/views/Editor.vue
Currently Topnav is showing wrong on editor page.
- Go to proposal editor.
- Publish button is there.
> fix: show editor topnav

- src/components/Block/SpaceFormStrategies.vue
- src/components/Block/StrategiesConfigurator.vue
- src/views/Create.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/591
- Go to space creation form, authenticators step.
- You can only add one authenticator of each type.
> feat: add unique constraint to authenticator strategies

- src/components/Block/SpaceFormNetwork.vue
- src/components/Block/StrategiesConfigurator.vue
- src/networks/evm/constants.ts
- src/networks/types.ts
- src/views/Create.vue
Display for strategies descriptions on space creation
> feat: add strategies descriptions

- src/views/Create.vue
> fix: prevent wrapping of menu tiles

- package.json
- src/composables/useActions.ts
- src/composables/useEditor.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/evm/actions.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/types.ts
- src/views/Editor.vue
- src/views/Proposal.vue
- yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/562
- Use local mana https://github.com/snapshot-labs/mana/pull/95
- Create proposal with space with some voting delay, for example there http://localhost:8080/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780 you have 4 hours.
- Go to proposal page within 4 hours signed in as proposal author.
- You can edit the proposal (button at the top).
- You can submit the new proposal.
- It gets updated after a while.
> feat: add ability to edit proposals

- src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/611
> chore: update Edit profile tooltip

- src/components/S/IStamp.vue
This PR adds background and border to IStamp component.
Closes: https://github.com/snapshot-labs/sx-ui/issues/600
Closes: https://github.com/snapshot-labs/sx-ui/issues/599
> feat: update IStamp styles to add border and background

- src/components/Block/SpaceFormValidation.vue
- src/components/Block/StrategiesConfigurator.vue
- src/components/StrategyButton.vue
- src/networks/evm/constants.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/601
- Go to space creation form.
- Go to validations.
- New layout is used, you can add validations.
> feat: use StrategyButton for validations

- src/components/Block/SpaceFormVoting.vue
- src/components/S/IDuration.vue
- src/components/S/IObject.vue
- src/components/Ui/Editable.vue
- src/networks/evm/constants.ts
- src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/597
> feat: add SIDuration input

- src/helpers/connectors.ts
Currently connecting with goerli we get lots of failed requests because we don't have goerli node defined. Also updated mainnet URL.
> feat: add walletconnect goerli RPC node

- package.json
- src/components/Modal/EditStrategy.vue
- src/networks/evm/actions.ts
- src/networks/evm/constants.ts
- src/networks/evm/index.ts
- src/networks/index.ts
- yarn.lock
This PR adds v0.5.0 contracts compatibility.
Closes: https://github.com/snapshot-labs/sx-ui/issues/650
Closes: https://github.com/snapshot-labs/sx-ui/issues/608
Depends on: https://github.com/snapshot-labs/sx.js/pull/193
- Link sx.js from PR above to sx-ui (run with `yarn dev --force`) **and mana - you need local mana with sx.js even though there are no changes on mana**.
- Use local mana.
- Create space, propose, vote.
> feat: add v0.5.0 compatibility

- src/components/Block/SpaceFormNetwork.vue
- src/composables/useTreasury.ts
- src/helpers/networks.json
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/common/graphqlApi/types.ts
- src/networks/evm/actions.ts
- src/networks/evm/constants.ts
- src/networks/evm/index.ts
- src/networks/index.ts
- src/networks/types.ts
- src/stores/proposals.ts
- src/types.ts
Resubmit of https://github.com/snapshot-labs/sx-ui/pull/654
I merged PRs in wrong order and [this PR](https://github.com/snapshot-labs/sx-ui/pull/654) ended up getting lost.
> feat: add sepolia support

- package.json
- src/composables/useActions.ts
- src/composables/useTreasury.ts
- src/helpers/networks.json
- src/helpers/pin.ts
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/evm/actions.ts
- src/networks/evm/helpers.ts
- src/networks/evm/index.ts
- src/networks/index.ts
- src/networks/starknet/index.ts
- src/types.ts
- yarn.lock
Tested:
- Creating new space.
- Proposing and voting (Voting power validation strategy, vanilla voting strategy).
- Execution (timelock execution).
Limitations:
- Sometimes IPFS takes long time to resolve making Spaces and Proposals slow to show up (it seems to be better now).
- Treasury doesn't show funds because Alchemy doesn't support Linea.
> feat: add Linea testnet support

- src/components/Modal/Votes.vue
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/types.ts
- src/views/Proposal.vue
- Change LIMIT to 3, and [modal height to 200px](https://github.com/snapshot-labs/sx-ui/blob/531f749b334e310fc2020c7eb06b7bc429eea7f1/src/components/Ui/Modal.vue#L102)
- Go there: http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845/proposal/3
- Click votes.
- New votes get loaded in.
- Scroll a bit.
- It triggers another load to fetch the rest.
> feat: add pagination to proposal votes modal

- src/networks/evm/index.ts
- src/networks/starknet/index.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/662
> fix: clear timer in waitForSpace

- package.json
- src/components/Ui/Dropdown.vue
- src/components/Ui/DropdownItem.vue
- src/views/Proposal.vue
- yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/674
Depends on: https://github.com/snapshot-labs/sx-ui/pull/666
- Disable linea.
- Create proposal.
- You can open dropdown.
> feat: add Dropdown

- src/App.vue
- src/composables/useTitle.ts
- src/views/Create.vue
- src/views/Editor.vue
- src/views/Explore.vue
- src/views/Proposal.vue
- src/views/Settings/Contacts.vue
- src/views/Settings/Spaces.vue
- src/views/Space/Delegates.vue
- src/views/Space/Overview.vue
- src/views/Space/Proposals.vue
- src/views/Space/SearchProposals.vue
- src/views/Space/Settings.vue
- src/views/Space/Treasury.vue
- src/views/User.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/663
Not using vueuse's useTitle as it doesn't work properly with vue-router navigation.
Implemented using simple custom composable.
> feat: add page titles

- src/components/Block/Actions.vue
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/types.ts
- src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/642
- Go there http://localhost:8080/#/sep:0x8e7793c005bb37c7b7b47c1ae980dc6ddd2edbf5/proposal/1 (within 4 hours).
> feat: add execution countdown for veto strategy

- src/components/Modal/Timeline.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/686
- Go to space with equal min/max durations and create new proposal (or visit existing if one was created with those settings) - http://localhost:8080/#/gor:0x62f8a028433d811cc0a63c974207276600322062/proposal/8
- Click on date to open timeline.
> feat: merge min end and max end into single step if same

- src/components/NftPreview.vue
- src/components/SpaceAvatar.vue
- src/components/Stamp.vue
- src/composables/useFavicon.ts
- src/helpers/utils.ts
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/common/graphqlApi/types.ts
- src/types.ts
- src/views/Proposal.vue
- src/views/Space.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/685
- Go there: http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845
- Avatar is used as favicon.
- Navigate to other space, new avatar is used.
- Go to non space view - default favicon is used.
> feat: use space avatar as favicon

- src/components/Block/SpaceFormProfile.vue
- src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/535
> feat: validate handle is not URL

- src/components/Results.vue
- src/views/Proposal.vue
This change how results are displaying, using an icon and new line for each choice
> style: improve display results

- src/components/Ui/Dropdown.vue
- src/components/Ui/Select.vue
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/types.ts
- src/stores/proposals.ts
- src/views/Space/Proposals.vue
- src/views/Space/SearchProposals.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/687
- Go to http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845/proposals
- Test different filters
> feat: add proposals filter

- src/components/SpaceCover.vue
- src/views/Space/Overview.vue
- src/views/User.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/619
Depends on: https://github.com/snapshot-labs/sx-ui/pull/678
- Set up like https://github.com/snapshot-labs/sx-ui/pull/678
- Go to space/user profile.
> feat: add border to cover photo

- src/components/Block/ExecutionEditable.vue
- src/components/ExecutionButton.vue
- src/components/Modal/VotingPower.vue
- src/components/Transaction.vue
- src/components/Ui/Select.vue
- src/components/VotingPowerIndicator.vue
- src/networks/common/graphqlApi/index.ts
- src/networks/types.ts
- src/stores/proposals.ts
- src/views/Editor.vue
- src/views/Space/Proposals.vue
- src/views/Space/SearchProposals.vue
Changed a bit the layout for the editor, now the layout is larger (same size than proposal content), the execution button are displayed one by line instead of 3 columns (this is to accommodate later with others execution like WalletConnect). I also changed the icon for send tokens and execution strategies.
You can test on this space with multiple executions:
http://localhost:8080/#/gor:0xdd3caa572b45e973d4b8652c973b40d0a6567fab/create
Also:
- Changed draggable to Draggable to fix warning.
- Changed "Voting power" label to "Your voting power"
- Change "All" to "Any" on status proposal filter
> style: improve editor page

- src/networks/common/graphqlApi/queries.ts
- src/networks/common/graphqlApi/types.ts
- src/types.ts
- src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/701
- Go to edited proposal: http://localhost:8080/#/sep:0x8e7793c005bb37c7b7b47c1ae980dc6ddd2edbf5/proposal/8
- You see edited label.
> feat: add edited indicator

- src/components/Markdown.vue
- src/components/Ui/Loading.vue
- src/composables/useMarkdownEditor.ts
- src/views/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/698
This PR adds image upload via drag and drop or clicking bottom bar similar to Github.
> feat: add image upload to editor

- package.json
- src/helpers/connectors.ts
- yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/710
- Try signing in with WalletConnect.
- Perform some actions on the UI.
> feat: upgrade to WalletConnect v2

- README.md
- package.json
- src/components/Ui/Editable.vue
- src/composables/useTreasury.ts
- src/composables/useWeb3.ts
- src/helpers/alchemy/index.ts
- src/helpers/connectors.ts
- src/helpers/networks.json
- src/networks/evm/actions.ts
- src/networks/evm/index.ts
- src/networks/index.ts
- src/types.ts
- src/views/Create.vue
- src/views/Space/Settings.vue
- yarn.lock
This PR add support for Polygon and Arbitrum.
> feat: add Polygon and Arbitrum

- package.json
- src/networks/starknet/actions.ts
- yarn.lock
Depends on: https://github.com/snapshot-labs/sx.js/pull/210
Depends on: https://github.com/snapshot-labs/sx-api/pull/184
- Modify space settings.
> feat(starknet): implement space settings

- src/components/Modal/EditSpace.vue
- src/components/S/IStampCover.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/722
> fix: keep previous cover when updating space metadata

- src/networks/starknet/actions.ts
- Propose there: http://localhost:8080/#/sn-tn:0x04b1953ac6bbe7a162d1afca0065bc82ba707501acbc01774cc1cf59721da6df
> fix: use voting power voting strategies when proposing

- package.json
- yarn.lock
Closes: https://github.com/snapshot-labs/sx-ui/issues/735
> fix: add salt to update proposal message

- src/components/Block/ExecutionEditable.vue
- src/components/Block/TokenPicker.vue
- src/components/Modal/SendToken.vue
- src/composables/useBalances.ts
- src/composables/useTreasury.ts
- src/helpers/alchemy/index.ts
- src/networks/evm/index.ts
- src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/723
Depends on: https://github.com/snapshot-labs/stamp/pull/88
- Run local stamp for logo support: https://github.com/snapshot-labs/stamp/pull/88
- Check http://localhost:8080/#/matic:0xa98d476118af1a2c9eab803db9688e33cf68435f/treasury
> feat: customize base token for each EVM network

- src/App.vue
- src/components/Block/Actions.vue
- src/components/Preview.vue
- src/components/Topnav.vue
- src/stores/contacts.ts
- src/stores/spaces.ts
- src/views/Settings/Spaces.vue
- src/views/Space/Treasury.vue
- vite.config.ts
Add support for swipe the left sidebar on mobile:
https://github.com/snapshot-labs/sx-ui/assets/16245250/60649bce-7eab-415a-a1cd-3437297bc8c6
> feat: add sidebar swipe on mobile

- src/networks/starknet/constants.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/749
> chore(sx-sn): remove vanilla authenticator

- src/networks/evm/constants.ts
- src/networks/starknet/constants.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/740
- http://localhost:8080/#/gor:0xf6dd0dda425f534a1d4d6ee56ba74a21c06cf9dd/settings
> chore: unify Avatar/Zodiac naming

- package.json
- src/components/Block/SpaceFormProfile.vue
- src/components/Modal/Delegate.vue
- src/components/Modal/EditSpace.vue
- src/components/Topnav.vue
- src/composables/useActions.ts
- src/composables/useTreasury.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/constants.ts
- src/helpers/utils.ts
- src/networks/common/graphqlApi/index.ts
- src/networks/common/graphqlApi/queries.ts
- src/networks/common/graphqlApi/types.ts
- src/networks/evm/actions.ts
- src/networks/starknet/actions.ts
- src/networks/types.ts
- src/router.ts
- src/types.ts
- src/views/Create.vue
- src/views/Space/Delegates.vue
- src/views/Space/Search.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/656
- Add delegation contract to your space (needs to be EVM based).
- Go to delegation settings.
- Click delegation button.
- You can delegate.
> feat: add delegation

- src/components/SpaceItem.vue
> chore: verify currentNetwork is defined

- src/components/Modal/SendToken.vue
- src/composables/useBalances.ts
- src/helpers/alchemy/index.ts
- src/helpers/constants.ts
- src/helpers/utils.ts
- src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/732
- Go to MATIC/ARB space: http://localhost:8080/#/matic:0x4d95a8be4f1d24d50cc0d7b12f5576fa4bbd892b/treasury
- Values are shown.
> feat: add treasury rates via CoinGecko

- src/components/MarkdownEditor.vue
- src/views/Editor.vue
Closes: https://github.com/snapshot-labs/sx-ui/issues/788
1. Go to proposal editor.
2. Editor still works.
> refactor: extract MarkdownEditor component

- src/components/Block/InfiniteScroller.vue
- src/composables/useDelegates.ts
- src/views/Proposal/Votes.vue
- src/views/Space/Delegates.vue
Closes: [#](https://github.com/snapshot-labs/sx-ui/issues/790)
1. Go to http://localhost:8080/#/arb1:0x2fb231a3ac7c40888d2e6773f5600851b0c20ce4/delegates
2. Try sorting by different values.
> feat: add toolbar to Delegates page

- package.json
- vite.config.ts
- yarn.lock
This is no longer needed.
1. App still works (in dev mode and after build).
> chore: remove node-globals-polyfill

- src/networks/offchain/index.ts
Change to new URL, More details: https://discord.com/channels/955773041898573854/1030772407226601522/1175036485842509884
> fix: change hub testnet URL

- src/networks/index.ts
- src/networks/starknet/actions.ts
- src/networks/starknet/constants.ts
- src/networks/starknet/index.ts
- src/types.ts
Closes: https://github.com/snapshot-labs/sx-ui/issues/850
Depends on: https://github.com/snapshot-labs/sx-api/pull/207
1. Use as usual. http://localhost:8080/#/sn-sep:0x03c6522894761d3d582f731e00a4d519db80dff32dc1d5b216c10fc4ec883432/proposal/1
> feat(starknet): add sepolia network support

- src/networks/starknet/index.ts
Didn't commit this change by mistake in previous PR.
> fix: update sn-sepolia starknet URL

- package.json
- src/components/Block/ExecutionEditable.vue
- src/components/Block/SpaceFormController.vue
- src/components/Block/SpaceFormNetwork.vue
- src/components/Block/SpaceFormStrategies.vue
- src/components/Block/SpaceFormValidation.vue
- src/components/Block/StrategiesConfigurator.vue
- src/components/MarkdownEditor.vue
- src/components/Modal/Account.vue
- src/components/S/IArray.vue
- src/components/S/IBoolean.vue
- src/components/S/IDuration.vue
- src/components/S/INumber.vue
- src/components/S/IObject.vue
- src/components/S/ISelect.vue
- src/components/S/IStamp.vue
- src/components/S/IStampCover.vue
- src/components/S/IString.vue
- src/components/S/IText.vue
- src/components/Ui/Select.vue
- vite.config.ts
- yarn.lock
This is now stable and recommended method of using model in components.
https://vuejs.org/guide/components/v-model.html
Upgraded deps to match new Vue version.
1. Everything works as it used to, probably the best flow is to test creating a space and creating a proposal.
> refactor: use defineModel
